# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: dotnet new bald
email: steve.bilogan@gmail.com
subtitle: A blog about .NET, Uno Platform, and other things I find interesting.
og_image: /assets/images/profile.png
image: /assets/images/profile.png
teaser: /assets/images/profile.png
repository: kazo0/kazo0.github.io
description: >- # this means to ignore newlines until "baseurl:"
  I'm Steve Bilogan, a Senior Engineer and one of the core maintainers of the open-source Uno Platform project. When not at my computer, I'm either watching the Montreal Canadiens lose or asleep on the couch with my wonderful wife, Michele, and our little monster, Penny.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kazo0.dev" # the base hostname & protocol for your site, e.g. http://example.com
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-C0L3NPFRW1"
twitter_username: BiloganSteve
github_username:  kazo0
name: Steve Bilogan
author:
  name: Steve Bilogan
  avatar: /assets/images/profile.png
  location: Kingston, Ontario
  links:
    - label: "kazo0"
      icon: "fa-brands fa-fw fa-square-github"
      url: "https://github.com/kazo0"
    - label: "@BiloganSteve"
      icon: "fa-brands fa-fw fa-square-x-twitter"
      url: "https://twitter.com/BiloganSteve"
    - label: "sbilogan"
      icon: "fa-brands fa-fw fa-inverse fa-linkedin"
      url: "https://www.linkedin.com/in/sbilogan"
    - label: "Sessionize"
      icon: "fa-solid fa-fw fa-microphone-lines"
      url: "https://sessionize.com/steve-bilogan/"
twitter:
  username: BiloganSteve
  card: summary_large_image
social:
  name: Steve Bilogan
  links:
    - https://twitter.com/BiloganSteve
    - https://www.linkedin.com/in/sbilogan
    - https://github.com/kazo0
google_site_verification: TpeQI87UtEWc5hC3Uzt01Cf6RH88ojPL7z6OQL0vp9U
github: [metadata]
author_profile: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
locale: "en-US"
search: true
head_scripts:
  - https://kit.fontawesome.com/7635bcfdad.js
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/profile.png
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true
      author_profile: true
      related: true
      toc: true
kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
