# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: dotnet new bald
email: steve.bilogan@gmail.com
tagline: A blog about .NET, Uno Platform, and other things I find interesting.
logo: _assets/images/profile.png
description: >- # this means to ignore newlines until "baseurl:"
  I'm Steve Bilogan, a Senior Engineer and one of the core maintainers of the open-source Uno Platform project. When not at my computer, I'm either watching the Montreal Canadiens lose or asleep on the couch with my wonderful wife, Michele, and our little monster, Penny.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kazo0.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BiloganSteve
github_username:  kazo0
image: /icon192.png
twitter:
  username: BiloganSteve
  image: /icon192.png
social:
  name: Steve Bilogan
  links:
    - https://twitter.com/BiloganSteve
    - https://www.linkedin.com/in/sbilogan
    - https://github.com/kazo0
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
