source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# gem "jekyll", "~> 4.3.2"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# Pinned to the version actions/jekyll-build-pages ships, so `bin/serve` renders
# with the same Jekyll the deploy uses. Bump both together.
gem "github-pages", "~> 232", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem "jekyll-remote-theme"
gem 'jekyll-include-cache'
gem 'jekyll-seo-tag'
gem 'jemoji'
gem 'jekyll-sitemap'

# webrick, csv, base64 and bigdecimal used to be declared here because Ruby 3.4
# dropped them as default gems and Jekyll 3.9.x didn't ask for them. Jekyll
# 3.10.0 declares csv and webrick itself, and activesupport brings base64 and
# bigdecimal, so naming them again only risks pinning a version the deploy
# image doesn't have.